### ISSUE TITLE
Illegal Repository

### ISSUE THREAD

**Issue by xbony2** [Dennisbonke/GregTech#1]
Publicly releasing this decompiled work of Greg's is kind of against the law, especially with you relicensing it. If you agree to delete this repository within 24 hours, I will not report it to GregoriusT.

Assuming GregoriusT learns of this and sends a DMCA, your account may be terminated, due to [previous infringement](https://github.com/github/dmca/blob/ba2e87dd6710ee2d89945ca9b713728e3344c086/2015-02-06-extrautilities.md). If you act now, you can avoid this.

-xbony2

**Comment by Dennisbonke** [comment]
will do right now.
